add views and test controller
Tavbulatov/Test-Guru pull request #8
Opened 2022-07-26 00:01 UTC by Tavbulatov

2022-07-26 06:57 UTC, VidgarVii requested changes

2022-07-26 06:57 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question_test = @test.id
это операция точно нужна? Еще тут явно нарушение нейменгов. Ид теста это точно не тест вопроса
то же самое на 13 строке

2022-07-26 06:57 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    redirect_to test_path(@question_test)
redirect_to test_path(@question.test)
и 44 строчка не нужна
инстанс переменные создаём только для того, чтобы потом с ней работать во вью

2022-07-26 06:57 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question_test = Test.find(@question.test_id)
тест можно получить так
@question.test

2022-07-27 14:39 UTC, VidgarVii requested changes

2022-07-27 14:39 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
запрос Test.find(params[:id]) дублируется. Стоит его вынести в колбек

2022-07-27 14:39 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_test, only: %i[index create new]
важно:
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2022-07-29 05:52 UTC, BubuntuClu commented on app/models/test.rb
> +                                     .order(title: :desc)
сортировку не надо помещать в скоуп
скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2022-07-29 05:52 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<%= render 'form' %>
вьюхи `edit/new` у тебя идентичные. в них можно оставить только `<%= render 'form' %>`, а все остальные вынести в `form`

2022-08-06 19:13 UTC, merged